version: '3.7'
services:
  go-grpc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang.grpc-service
#    ports:
#      - "8087:80"
    networks:
      - default
    volumes:
      - ./:/go/src/grpc-service
    environment:
      GOPATH: "/go:/go/src/grpc-service"
